export const GAME_WIDTH = 1280;
export const GAME_HEIGHT = 800;
export const REEL_COUNT = 4;
export const SYMBOLS_PER_REEL = 6;
export const SYMBOL_SIZE = 150;
export const REEL_HEIGHT = SYMBOL_SIZE;
export const REEL_SPACING = 10;
export const SPIN_START_SPEED = 50; // Pixels per frame
export const SLOWDOWN_RATE = 0.99; // Rate at which the reel slows down